version: '3.8'

services:
  # Databases
  mysql:
    image: mysql:8.0
    container_name: gigalike-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: gigalike_auth
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gigalike-network

  mongodb:
    image: mongo:7.0
    container_name: gigalike-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - gigalike-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: gigalike-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gigalike-network

  redis:
    image: redis:7.2-alpine
    container_name: gigalike-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - gigalike-network
    command: redis-server --appendonly yes

  # Infrastructure Services
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: gigalike-eureka
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD:-password}
    ports:
      - "${EUREKA_SERVER_PORT:-8761}:8761"
    networks:
      - gigalike-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: gigalike-config-server
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      CONFIG_PASSWORD: ${CONFIG_PASSWORD:-configpass}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:${EUREKA_PASSWORD:-password}@eureka-server:8761/eureka/
    ports:
      - "${CONFIG_SERVER_PORT:-8888}:8888"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - gigalike-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: gigalike-api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:${EUREKA_PASSWORD:-password}@eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    ports:
      - "${API_GATEWAY_PORT:-8080}:8080"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - gigalike-network

  # Business Services
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: gigalike-auth-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:${EUREKA_PASSWORD:-password}@eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    ports:
      - "${AUTH_SERVICE_PORT:-8081}:8081"
    depends_on:
      - mysql
      - config-server
      - eureka-server
    networks:
      - gigalike-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: gigalike-product-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:${EUREKA_PASSWORD:-password}@eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    ports:
      - "${PRODUCT_SERVICE_PORT:-8082}:8082"
    depends_on:
      - mysql
      - config-server
      - eureka-server
    networks:
      - gigalike-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: gigalike-order-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:${EUREKA_PASSWORD:-password}@eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    ports:
      - "${ORDER_SERVICE_PORT:-8083}:8083"
    depends_on:
      - mysql
      - config-server
      - eureka-server
    networks:
      - gigalike-network

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: gigalike-payment-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:${EUREKA_PASSWORD:-password}@eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    ports:
      - "${PAYMENT_SERVICE_PORT:-8084}:8084"
    depends_on:
      - mongodb
      - config-server
      - eureka-server
    networks:
      - gigalike-network

  platform-service:
    build:
      context: ./platform-service
      dockerfile: Dockerfile
    container_name: gigalike-platform-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:${EUREKA_PASSWORD:-password}@eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    ports:
      - "${PLATFORM_SERVICE_PORT:-8086}:8086"
    depends_on:
      - mongodb
      - rabbitmq
      - redis
      - config-server
      - eureka-server
    networks:
      - gigalike-network

volumes:
  mysql_data:
  mongodb_data:
  rabbitmq_data:
  redis_data:

networks:
  gigalike-network:
    driver: bridge