server:
  port: ${MARKETING_SERVER_PORT}

spring:
  data:
    mongodb:
      authentication-database: ${MONGO_DB_AUTHEN}
      database: ${MONGO_DB_MARKETING}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

feign:
  auth-service:
    url: ${AUTH_SERVICE_URL}
  platform-service:
    url: ${PLATFORM_SERVICE_URL}
