server:
  port: ${PLATFORM_SERVICE_PORT}

spring:
  data:
    mongodb:
      authentication-database: ${MONGO_DB_AUTHEN}
      database: ${MONGO_DB_PLATFORM}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

feign:
  auth-service:
    url: ${AUTH_SERVICE_URL}

otp:
  expire_time: ${OTP_EXPIRE_TIME}
  length:  ${OTP_LENGTH}
redis:
  host: ${REDIS_HOST}
  port:  ${REDIS_PORT}

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}

notification:
  discord:

  email:
    from: ${NOTIFICATION_EMAIL_FROM}
  telegram:
    token: ${TELEGRAM_BOT_TOKEN}
    group-id: ${TELEGRAM_GROUP_ID}