server:
  port: ${CONFIG_SERVER_PORT}

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config-repo/
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  security:
    user:
      name: ${CONFIG_NAME}
      password: ${CONFIG_PASSWORD}

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER_CONFIG_SERVER}
    fetch-registry: ${EUREKA_FETCH_REGISTRY_CONFIG_SERVER}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS}

management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: env, health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: ${LOG_LEVEL}

